import type { LucideIcon } from "lucide-react";
import { BriefcaseBusiness, ShieldCheck, SquareUserRound, UserCog, UserRound } from "lucide-react";

export type UserStatus = "Active" | "Pending invite" | "Deactivated" | "Locked" | "Suspended";

const teamValues = [
  "Curriculum",
  "Platform",
  "Support",
  "Finance",
  "Marketing",
  "Compliance",
] as const;

export type UserTeam = (typeof teamValues)[number];

export type UserRow = {
  email: string;
  joinedDate: string;
  lastActive: number;
  name: string;
  role: string;
  status: UserStatus;
  team: UserTeam;
  workspace: string[];
};

export const users: UserRow[] = [
  {
    name: "Olivia Rhye",
    email: "olivia.rhye@bytestart.edu",
    role: "Course Owner",
    status: "Active",
    team: "Curriculum",
    workspace: ["ByteStart Academy", "Content Hub"],
    joinedDate: "24 Jun 2024, 9:23 AM",
    lastActive: 0,
  },
  {
    name: "Phoenix Baker",
    email: "phoenix.baker@bytestart.edu",
    role: "Admin",
    status: "Active",
    team: "Platform",
    workspace: ["ByteStart Academy"],
    joinedDate: "15 Mar 2023, 2:45 PM",
    lastActive: 5,
  },
  {
    name: "Lana Steiner",
    email: "lana.steiner@bytestart.edu",
    role: "Finance Officer",
    status: "Active",
    team: "Finance",
    workspace: ["Finance Ops"],
    joinedDate: "10 Apr 2022, 11:30 AM",
    lastActive: 14 * 24 * 60,
  },
  {
    name: "Demi Wilkinson",
    email: "demi.wilkinson@bytestart.edu",
    role: "Admin",
    status: "Locked",
    team: "Platform",
    workspace: ["ByteStart Academy", "System Admin"],
    joinedDate: "28 Feb 2023, 6:15 PM",
    lastActive: 60,
  },
  {
    name: "Candice Wu",
    email: "candice.wu@bytestart.edu",
    role: "Support Staff",
    status: "Active",
    team: "Support",
    workspace: ["ByteStart Academy"],
    joinedDate: "19 May 2024, 7:55 AM",
    lastActive: 2 * 60,
  },
  {
    name: "Natali Craig",
    email: "natali.craig@bytestart.edu",
    role: "Content Editor",
    status: "Pending invite",
    team: "Curriculum",
    workspace: ["Content Hub"],
    joinedDate: "03 Jan 2024, 12:05 PM",
    lastActive: 90 * 24 * 60,
  },
  {
    name: "Drew Cano",
    email: "drew.cano@bytestart.edu",
    role: "Calon Pelanggan (Public)",
    status: "Active",
    team: "Marketing",
    workspace: ["ByteStart Academy"],
    joinedDate: "21 Jul 2023, 8:40 PM",
    lastActive: 3 * 60,
  },
  {
    name: "Orlando Diggs",
    email: "orlando.diggs@bytestart.edu",
    role: "Pelanggan (Student)",
    status: "Deactivated",
    team: "Support",
    workspace: ["ByteStart Academy"],
    joinedDate: "16 Sep 2023, 3:25 PM",
    lastActive: 6,
  },
  {
    name: "Andi Lane",
    email: "andi.lane@bytestart.edu",
    role: "Pelanggan (Student)",
    status: "Active",
    team: "Support",
    workspace: ["ByteStart Academy"],
    joinedDate: "04 Nov 2022, 9:50 AM",
    lastActive: 12,
  },
  {
    name: "Kate Morrison",
    email: "kate.morrison@bytestart.edu",
    role: "Admin",
    status: "Active",
    team: "Platform",
    workspace: ["ByteStart Academy"],
    joinedDate: "30 Dec 2023, 4:35 PM",
    lastActive: 30,
  },
  {
    name: "Alec Whitten",
    email: "alec.whitten@bytestart.edu",
    role: "Content Editor",
    status: "Suspended",
    team: "Curriculum",
    workspace: ["Content Hub"],
    joinedDate: "12 Feb 2024, 10:20 AM",
    lastActive: 8 * 24 * 60,
  },
  {
    name: "Ariana Decker",
    email: "ariana.decker@bytestart.edu",
    role: "Pelanggan (Student)",
    status: "Active",
    team: "Curriculum",
    workspace: ["ByteStart Academy"],
    joinedDate: "08 Aug 2023, 1:10 PM",
    lastActive: 24 * 60,
  },
  {
    name: "Steven Tey",
    email: "steven.tey@bytestart.edu",
    role: "Calon Pelanggan (Public)",
    status: "Pending invite",
    team: "Marketing",
    workspace: ["ByteStart Academy"],
    joinedDate: "17 Jan 2024, 5:45 PM",
    lastActive: 90 * 24 * 60,
  },
  {
    name: "Lori Bryson",
    email: "lori.bryson@bytestart.edu",
    role: "Finance Officer",
    status: "Active",
    team: "Finance",
    workspace: ["Finance Ops"],
    joinedDate: "02 Oct 2023, 11:15 AM",
    lastActive: 45,
  },
  {
    name: "Koray Okumus",
    email: "koray.okumus@bytestart.edu",
    role: "Admin",
    status: "Active",
    team: "Platform",
    workspace: ["ByteStart Academy", "System Admin"],
    joinedDate: "22 May 2024, 8:30 AM",
    lastActive: 10,
  },
  {
    name: "Josh Miller",
    email: "josh.miller@bytestart.edu",
    role: "Pelanggan (Student)",
    status: "Active",
    team: "Curriculum",
    workspace: ["ByteStart Academy"],
    joinedDate: "14 Jul 2023, 6:05 PM",
    lastActive: 4 * 60,
  },
  {
    name: "Mollie Hall",
    email: "mollie.hall@bytestart.edu",
    role: "Pelanggan (Student)",
    status: "Deactivated",
    team: "Support",
    workspace: ["ByteStart Academy"],
    joinedDate: "26 Nov 2022, 3:40 PM",
    lastActive: 21 * 24 * 60,
  },
  {
    name: "Rene Wells",
    email: "rene.wells@bytestart.edu",
    role: "Support Staff",
    status: "Active",
    team: "Support",
    workspace: ["ByteStart Academy"],
    joinedDate: "11 Apr 2024, 9:05 AM",
    lastActive: 18,
  },
  {
    name: "Rylee Howard",
    email: "rylee.howard@bytestart.edu",
    role: "Calon Pelanggan (Public)",
    status: "Locked",
    team: "Marketing",
    workspace: ["ByteStart Academy"],
    joinedDate: "09 Sep 2023, 12:25 PM",
    lastActive: 2 * 24 * 60,
  },
  {
    name: "Sienna Hewitt",
    email: "sienna.hewitt@bytestart.edu",
    role: "Admin",
    status: "Active",
    team: "Platform",
    workspace: ["ByteStart Academy", "System Admin"],
    joinedDate: "05 Dec 2023, 2:15 PM",
    lastActive: 0,
  },
  {
    name: "Noah Pierre",
    email: "noah.pierre@bytestart.edu",
    role: "Pelanggan (Student)",
    status: "Active",
    team: "Curriculum",
    workspace: ["ByteStart Academy"],
    joinedDate: "18 Jun 2024, 4:50 PM",
    lastActive: 7,
  },
  {
    name: "Eve Lechner",
    email: "eve.lechner@bytestart.edu",
    role: "Pelanggan (Student)",
    status: "Suspended",
    team: "Curriculum",
    workspace: ["ByteStart Academy"],
    joinedDate: "01 Mar 2023, 10:10 AM",
    lastActive: 30 * 24 * 60,
  },
  {
    name: "Zahir McClure",
    email: "zahir.mcclure@bytestart.edu",
    role: "Admin",
    status: "Active",
    team: "Platform",
    workspace: ["ByteStart Academy", "System Admin"],
    joinedDate: "07 Feb 2024, 7:20 PM",
    lastActive: 60,
  },
  {
    name: "Mia Romberg",
    email: "mia.romberg@bytestart.edu",
    role: "Finance Officer",
    status: "Pending invite",
    team: "Finance",
    workspace: ["Finance Ops"],
    joinedDate: "29 Apr 2024, 11:55 AM",
    lastActive: 90 * 24 * 60,
  },
  {
    name: "Nico Arendt",
    email: "nico.arendt@bytestart.edu",
    role: "Pelanggan (Student)",
    status: "Active",
    team: "Support",
    workspace: ["ByteStart Academy"],
    joinedDate: "13 May 2024, 6:35 PM",
    lastActive: 25,
  },
];

export const filters = {
  role: [
    "All",
    "Course Owner",
    "Admin",
    "Pelanggan (Student)",
    "Calon Pelanggan (Public)",
    "Content Editor",
    "Support Staff",
    "Finance Officer",
  ],
  team: ["All", ...teamValues],
  status: ["All", "Active", "Pending invite", "Deactivated", "Locked", "Suspended"],
  workspace: ["All", "ByteStart Academy", "Content Hub", "System Admin", "Finance Ops"],
};

export const roleMeta: Record<string, { className: string; icon: LucideIcon }> = {
  "Course Owner": { className: "text-emerald-400", icon: SquareUserRound },
  Admin: { className: "text-amber-400", icon: UserCog },
  "Pelanggan (Student)": { className: "text-[#DDA5FF]", icon: UserRound },
  "Calon Pelanggan (Public)": { className: "text-slate-400", icon: UserRound },
  "Content Editor": { className: "text-cyan-400", icon: BriefcaseBusiness },
  "Support Staff": { className: "text-sky-400", icon: ShieldCheck },
  "Finance Officer": { className: "text-[#FAEB92]", icon: BriefcaseBusiness },
};

export const statusMeta: Record<UserStatus, { badgeClass: string; dotClass: string }> = {
  Active: {
    badgeClass: "border-emerald-500/20 bg-emerald-500/10 text-emerald-600 dark:text-emerald-400",
    dotClass: "bg-emerald-500",
  },
  "Pending invite": {
    badgeClass: "border-amber-500/20 bg-amber-500/10 text-amber-600 dark:text-amber-400",
    dotClass: "bg-amber-500",
  },
  Deactivated: {
    badgeClass: "border-border bg-muted/50 text-muted-foreground",
    dotClass: "bg-muted-foreground",
  },
  Locked: {
    badgeClass: "border-destructive/20 bg-destructive/10 text-destructive",
    dotClass: "bg-destructive",
  },
  Suspended: {
    badgeClass: "border-orange-500/20 bg-orange-500/10 text-orange-600 dark:text-orange-400",
    dotClass: "bg-orange-500",
  },
};
